#!/bin/csh -f
#
set s = "`pwd`"
set h = $s:t

set add = '>&'
set q = '"'
set pbsop = ""
set Ochk = ""
set clean = "clean"
set save = "full"
unalias mv
unalias cp
unalias rm

foreach o ( $* )
  if ( "$o" == "-ochk" ) then
    set Ochk = "check"
  else if ( "$o" == "-noclean" ) then
    set clean = "noclean"
  else if ( "$o" == "-brief" ) then
    set save = "brief"
  else
    set pbsop = "$pbsop $o"
  endif
end

foreach ee ( 0.940 0.955 0.970 0.985 1.000 1.015 1.030 1.045 1.060 1.075 )
    set d = V"$ee"

        if ( -e $d ) then
        if ( "$Ochk" != "check" || ! ( -e $d/OSZICAR ) || -z $d/OSZICAR ) then
        cd $d

vasppbs $pbsop >B-"$h"
set WORKDIR = "`pwd`"
set RUNDIR = '$tmpdir'
set VSPCMD = '$VSPCMD'

cat <<end.end >>B-"$h"
if ( !(-e $RUNDIR) ) mkdir $RUNDIR
cd $WORKDIR
unalias cp
unalias mv
#cp -f POTCAR   $RUNDIR

if ( -e ../tplate/POTCAR ) then
  cp -f ../tplate/POTCAR $RUNDIR
else if ( -e ../tplate/POTCAR.gz ) then
  zcat ../tplate/POTCAR.gz   >$RUNDIR/POTCAR
else if ( -e ../../POTCAR.gz ) then
  zcat ../../POTCAR.gz   >$RUNDIR/POTCAR
endif

cp -f ../tplate.Phonon/INCAR    $RUNDIR/INCAR
cp -f ../tplate.Phonon/KPOINTS  $RUNDIR/.
cp -f POSCAR   $RUNDIR/POSCAR
cd $RUNDIR

$VSPCMD $add $RUNDIR/B-"$h".error

cp -f OSZICAR $WORKDIR/.
cp -f CONTCAR $WORKDIR/.
cp -f OUTCAR $WORKDIR/.
cp -f vasprun.xml $WORKDIR/.

cd $WORKDIR
if ( -e OUTCAR ) then
	gzip -f DOSCAR
    endif
endif
end.end

	qsub B-"$h"
        cd ..
	endif
	endif
end

