#!/bin/csh -f
#

unalias cp
unalias mv
unalias rm
set ATOM = "Ni_pv"

set cpara = `ecmd -fF -BMvol -calmin -xlat lat | grep "Optimized xmin=" | awk '{print $3}'`

foreach option ( $* )
  if (x$1 == "x-h") then
    echo "USAGE: vcmd [value of lat] "
    exit
  else if (x$1 == "x-lat") then
    shift
    set cpara = "$1"
    if ( $#argv != 0 ) shift
  else if ($#argv != 0) then
    set cpara = "$1"
    if ( $#argv != 0 ) shift
  endif
end

set ppp = "POSCAR"
if ( ! -e $ppp ) then
  set ppp = "V1.000/POSCAR"
endif
if ( ! -e $ppp ) then
  set ppp = "V1.000/CONTCAR"
endif
if ( ! -e $ppp ) then
  echo "CANNOT find POSCAR!"
  exit
endif

set line = `head -6 $ppp | tail -1`
set _x = `echo $line | awk '{print $1}' | sed 's/[^0-9]//g'`
if ( "$_x" == "" ) then
    set NAT = `head -7 $ppp | tail -1`
else
    set NAT = `head -6 $ppp | tail -1`
endif

set natom = 0
set ntype = 0
foreach n ( $NAT )
    @ natom = "$natom" + "$n" 
    @ ntype = "$ntype" + 1
end

set p = '"'
set n = 0
echo >t.m.p.$$
foreach ee ( 0.940 0.955 0.970 0.985 1.000 1.015 1.030 1.045 1.060 1.075 )
    @ n = "$n" + 1
    set d = V"$ee"
    echo $ee $p$d/CONTCAR$p >>t.m.p.$$
end

if ( ! ( -e E ) ) mkdir E
pcoor -cpara $cpara -n $n -ntype $ntype -atom $ATOM -nat $NAT <t.m.p.$$ >E/POSCAR
mv str_t.m.p.out E/str.out
rm -f t.m.p.$$

cp -f tplate/INCAR E
cp -f tplate/POTCAR.gz E
cp -f tplate/KPOINTS E

cd E
grep -v NSW INCAR | grep -v ISIF >t.m.p.file
echo "NSW=30" >>t.m.p.file
echo "ISIF=3" >>t.m.p.file
mv -f t.m.p.file INCAR

