#!/bin/csh -f
#
set s = "`pwd`"
set h = $s:t

unalias cp

    set d = E

        cd $d

set hhhh = $HOME"/"
set pwdc = `pwd`
set Name = $pwdc:t
set tpwd = `echo $pwdc | sed "s|$hhhh||g;s|/|_|g"`
set tmpdir = "/scratch/`whoami`/$tpwd"

	  set cfile = "$tmpdir/CONTCAR"
	  set ofile = "$tmpdir/OSZICAR"
	  if ( -e $cfile ) then
            cp $cfile .
            cp $ofile .
	  endif
        cd ..

