#!/bin/csh -f
#
set s = "`pwd`"
set h = $s:t

set dollar1 = '$1'
set add = '>&'
set q = '"'
set pbsop = ""
set Ochk = ""
set clean = "clean"
set save = "full"
unalias mv
unalias cp
unalias rm

foreach o ( $* )
  if ( "$o" == "-ochk" ) then
    set Ochk = "check"
  else if ( "$o" == "-brief" ) then
    set save = "brief"
  else if ( "$o" == "-noclean" ) then
    set clean = "noclean"
  else
    set pbsop = "$pbsop $o"
  endif
end

foreach ee ( 0.940 0.955 0.970 0.985 1.000 1.015 1.030 1.045 1.060 1.075 )
    set d = V"$ee"

        set run = 0
        if ( -e $d ) then
        if ( "$Ochk" == "check" && -e $d/OSZICAR ) then
          set run = `grep -v '^$' $d/OSZICAR | tail -1 | grep E0 | wc -l | awk '{print $1}'`
        endif
        if ( "$Ochk" != "check" || $run == 0 ) then
        cd $d

vasppbs $pbsop >B-"$h"
set WORKDIR = "`pwd`"
set RUNDIR = '$tmpdir'
set VSPCMD = '$VSPCMD'

cat <<end.end >>B-"$h"
if ( !(-e $RUNDIR) ) mkdir $RUNDIR
cd $WORKDIR
unalias cp
unalias mv
cp -f KPOINTS  $RUNDIR
#cp -f POTCAR   $RUNDIR

if ( -e ../tplate/POTCAR ) then
  cp -f ../tplate/POTCAR   $RUNDIR
else if ( -e ../tplate/POTCAR.gz ) then
  zcat ../tplate/POTCAR.gz   >$RUNDIR/POTCAR
else if ( -e ../../POTCAR.gz ) then
  zcat ../../POTCAR.gz   >$RUNDIR/POTCAR
endif

cp -f INCAR    $RUNDIR

if ( -e CONTCAR ) then
  if ( -z CONTCAR ) then 
    cp -f POSCAR   $RUNDIR
  else
    cp -f CONTCAR   $RUNDIR/POSCAR
  endif
else    
  cp -f POSCAR   $RUNDIR
endif

cd $RUNDIR

$VSPCMD $add $RUNDIR/B-"$h".error

if ( ! -z OSZICAR ) cp -f OSZICAR $WORKDIR/.
if ( ! -z CONTCAR ) cp -f CONTCAR $WORKDIR/.

if ( "$save" == "full" ) then
  if ( ! -z OUTCAR ) cp -f OUTCAR $WORKDIR/.
  if ( ! -z DOSCAR ) cp -f DOSCAR $WORKDIR/.
else
  if ( ! -z OUTCAR ) tail -500 OUTCAR >$WORKDIR/OUTCAR
endif

if ( "$clean" == "clean" && "$WORKDIR" != "$RUNDIR" ) then
  set done = '\`grep -v \'\^\$\' $WORKDIR/OSZICAR | tail -1 | grep E0 | wc -l | awk "{print $dollar1}"\`'
  set run = "\$done"
  if ( "$RUNDIR":h != "$HOME" && $q\$run$q != $q"0"$q ) then
    rm $RUNDIR/*
    rmdir $RUNDIR
  endif
endif
cd $WORKDIR
if ( -e OUTCAR ) then
    if ( ! -z OUTCAR ) then
        if ( -e OUTCAR.gz ) mv OUTCAR.gz OUTCAR.gz.old
        gzip OUTCAR
        if ( -e DOSCAR.gz ) mv DOSCAR.gz DOSCAR.gz.old
        gzip DOSCAR
    endif
endif
cp $RUNDIR/B-"$h".error .
end.end

        qsub B-"$h"
        cd ..
        endif
        endif
end

