#!/bin/csh -f
#

set OFILE = "OSZICAR"
set CFILE = "CONTCAR"

set unit = eV

set FUNC = "-BMvol"
set XRANGE = ""
set PCMD = ""
set xlat = "lat"

foreach option ( $* )
  if (x$1 == "x-h") then
    echo "USAGE: ecmd     [ OSZICAR ]"
    echo "                [-natom natom ]"
    echo "                [-m ]"
    exit
  else if (x$1 == "x-mag") then
    shift
    set magnetic
    continue
  else if (x$1 == "x-weight") then
    shift
    set weight
    continue
  else if (x$1 == "x-xRange") then
    shift
    set XRange = "-xRange \[$1\]"
    shift
    continue
  else if (x$1 == "x-fF") then
    shift
    set FUNC = "$1"
    shift
    continue
  else if (x$1 == "x-unit") then
    shift
    set unit = $1
    shift
    continue
  else if (x$1 == "x-eV") then
    shift
    set unit = eV
    continue
  else if (x$1 == "x-Rydberg") then
    shift
    set unit = Rydberg
    continue
  else if (x$1 == "x-lat") then
    shift
    set xlat = "lat"
    continue
  else if (x$1 == "x-vol") then
    shift
    set xlat = "vol"
    continue
  else if (x$1 == "x-natom") then
    shift
    set natom = "$1"
    shift
    continue
  else if (x$1 == "x-POSCAR") then
    shift
    set CFILE = "$1"
    shift
    continue
  else if (x$1 == "x-OSZICAR") then
    shift
    set OFILE = "$1"
    shift
    continue
  else if (x$1 != "x") then
    set PCMD = "$PCMD $1"
    if ( $#argv != 0 ) shift
  endif
end

echo >fit22.dat 

foreach ee ( 1.000 )
    set d = V"$ee"
    set ofi = $d/$OFILE
    set ofc = $d/$CFILE
   if ( -e $ofi ) then

set line = `head -6 $ofc | tail -1`
set _x = `echo $line | awk '{print $1}' | sed 's/[^0-9]//g'`
if ( "$_x" == "" ) then
  set line = `head -7 $ofc | tail -1`
endif

set natom = `echo $line | awk '{ nn=0; for (i=1; i<=NF; i++) nn += $i; print nn;}'`

      set et = `grep "E0=" $ofi | tail -1 | awk '{print $5}'`
      if ( $?magnetic ) \
        set em = `grep "E0=" $ofi | tail -1 | awk '{print $10}'`
      if ( $et != "" ) then
        set e = `ari -n $et/$natom`
	set a = `head -2 $ofc | tail -1`
        set tmp = `vasp_volume <$ofc`
        set v = `ari -n $tmp / $natom`
	if ( $xlat == "lat" ) set v = $ee
	if ( $unit == Rydberg ) then
	    set e = `ari -n $e/13.6058 -2`
	    set v = `ari -n $a/.529177`
	endif
        if ( $?magnetic ) then
          echo " $v $e $em" >>fit22.dat
        else
          echo " $v $e" >>fit22.dat
        endif
      endif
    endif
end

if ($?weight) TextEdit fit22.dat
YWfit $FUNC $XRANGE $PCMD <fit22.dat

echo ""
cat fit22.dat
