#!/bin/csh -f
#
set SXYZ = ""
set CSTN = ""
set VFIX = ""
set STRAIN = ""

foreach option ( $* )
  if (x$1 == "x-a") then
    set CSTN = "-a"
    if ( $#argv != 0 ) shift
    continue
  else if (x$1 == "x-b") then
    set CSTN = "-b"
    if ( $#argv != 0 ) shift
    continue
  else if (x$1 == "x-c") then
    set CSTN = "-c"
    if ( $#argv != 0 ) shift
    continue
  else if (x$1 == "x-strain") then
    shift
    set STRAIN="-strain $1"
    shift
    continue
  else if (x$1 == "x-x") then
    set SXYZ = "-x"
    if ( $#argv != 0 ) shift
    continue
  else if (x$1 == "x-y") then
    set SXYZ = "-y"
    if ( $#argv != 0 ) shift
    continue
  else if (x$1 == "x-z") then
    set SXYZ = "-z"
    if ( $#argv != 0 ) shift
    continue
  else if (x$1 == "x-vfix") then
    set VFIX = "-vfix"
    if ( $#argv != 0 ) shift
    continue
  else if (x$1 != "x") then
    if ( $#argv != 0 ) shift
  endif
end

foreach ee ( 1.000 )
    set d = V"$ee"
    if ( ! -d $d ) then
        mkdir $d
        echo create $d...
    else
        echo renew $d...
    endif
        cd $d
        cp -f ../tplate/INCAR .
#        cp -f ../tplate/POTCAR .
        cp -f ../tplate/KPOINTS .
	/gpfs/home/yuw3/bin/VOLVASP/lattice $ee $CSTN $SXYZ $VFIX $STRAIN <../tplate/POSCAR >POSCAR
       	cd ..
end

