#!/bin/csh
#PBS -N BExamplesdft
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:59:00
cd $PBS_O_WORKDIR
set VSPCMD = "vasp_std"
module load intel impi mkl vasp
set tmpdir = "/gpfs/scratch/yuw3/work_dfttk_Examples"
unalias cp
unalias rm
cd /storage/work/y/yuw3/dfttk/Examples
#export LC_ALL='en_US.utf8'
setenv LC_ALL en_US.utf8
dfttk thfind -py -td -50 -plot "find_or_DFT" -eq 4 -renew -get -ss 30
dfttk thfind -py -td -50 -plot "find_or_DFT" -fitF -renew -get -ss 30
