"""
The sqs_db module handles creating and interacting with an SQS database of pymatgen-serialized SQS.

There are helper functions for converting SQS generated by mcsqs in ATAT to pymatgen Structure
objects that  serialization.

The sublattice and types are the same as used in ATAT, where `a_B` corresponds to atom `B` in
sublattice `a`. Due to the way dummy species are implemented in pymatgen, these species in pymatgen
Structures are renamed to `Xab`, which similarly corresponds to atom `B` in sublattice `a`.

In general, the workflow to create a database is to use the helper functions to
1. convert the lattice.in ATAT files to CIFs with renaming
2. create Structure objects from those CIFs, removing oxidation states (no helper function)
3. write those Structures to the database
4. persist the database to a path (no helper function)

Later, the database can be constructed again from the path, added to (steps 1-3) and persisted again.

To use the database, the user calls the `structures_from_database` helper function to generate a list
of all the SQS that match the endmember symmetry, sublattice model (and site ratios) that define a
phase. This is intentionally designed to match the syntax used to describe phases in ESPEI. Each of
the resulting Structure objects can be made concrete using functions in `prlworkflows.sqs`.
"""

from tinydb import TinyDB
from prlworkflows.sqs import SQS


def latt_in_to_cif(atat_lattice_in, rename=False):
    """
    Convert a string-like ATAT-style lattice.in to a CIF string.

    Note
    ----
    This method requires that ATAT is installed and str2cif is in your path.

    Parameters
    ----------
    atat_lattice_in : str
        String-like of a lattice.in in the ATAT format.
    rename : bool
        If True, SQS format element names will be renamed, e.g. `a_B` -> `Xab`. Default is False.

    Returns
    -------
    str
        String of the CIF version of the Structure.
    """
    pass


def SQSDatabase(path):
    """
    Convienence function to create a TinyDB for the SQS database found at `path`.

    Parameters
    ----------
    path : path-like of the folder containing the SQS database.

    Returns
    -------
    TinyDB
        Database of abstract SQS.
    """
    pass


def structure_to_database(db, structure):
    """Insert a Structure object with added metadata into the passed db.

    See the module definition for the database schema.

    Parameters
    ----------
    db : TinyDB
        TinyDB database of the SQS database
    structure : SQS
        Abstract SQS object with mixing sublattice species named in the format `Xab` for a mixing species
        `B` on sublattice `a`.
    """
    pass


def structures_from_database(db, symmetry, subl_model, subl_site_ratios):
    """Returns a list of Structure objects from the db that match the criteria.

    The returned list format supports matching SQS to phases that have multiple solution sublattices
    and the inclusion of higher and lower ordered SQS that match the criteria.

    Parameters
    ----------
    db : TinyDB
        TinyDB database of the SQS database
    symmetry : str
        Spacegroup symbol for a non-mixing endmember as in pymatgen, e.g. 'Pm-3m'.
    subl_model : [[str]]
        List of strings of species names, in the style of ESPEI `input.json`. This sublattice model
        can be of higher dimension than the SQS. Outer dimension should be the same length as subl_site_ratios.
    subl_site_ratios : [[float]]
        Site ratios of each sublattice. Outer dimension should be the same length as subl_model.

    Returns
    -------
    [SQS]
        Abstract SQSs that match the symmetry and sublattice model.
    """
    pass
