#!/bin/csh
#PBS -N BV1.075Ni-Ch
#PBS -A open
#PBS -l nodes=1:ppn=4
#PBS -l walltime=48:00:00
cd $PBS_O_WORKDIR
set VSPCMD = "vasp_std"
module load intel impi mkl vasp
set tmpdir = "/gpfs/scratch/yuw3/work_dfttk_Examples_Ni-CheckNFree4_V1.075"
unalias cp
unalias rm
if ( !(-e $tmpdir) ) mkdir $tmpdir
cd /storage/work/y/yuw3/dfttk/Examples/Ni-CheckNFree4/V1.075
unalias cp
unalias mv
#cp -f POTCAR   $tmpdir

if ( -e ../tplate/POTCAR ) then
  cp -f ../tplate/POTCAR $tmpdir
else if ( -e ../tplate/POTCAR.gz ) then
  zcat ../tplate/POTCAR.gz   >$tmpdir/POTCAR
else if ( -e ../../POTCAR.gz ) then
  zcat ../../POTCAR.gz   >$tmpdir/POTCAR
endif

cp -f ../tplate.Phonon/INCAR    $tmpdir/INCAR
cp -f ../tplate.Phonon/KPOINTS  $tmpdir/.
cp -f POSCAR   $tmpdir/POSCAR
cd $tmpdir

$VSPCMD >& $tmpdir/B-"Ni-CheckNFree4".error

cp -f OSZICAR /storage/work/y/yuw3/dfttk/Examples/Ni-CheckNFree4/V1.075/.
cp -f CONTCAR /storage/work/y/yuw3/dfttk/Examples/Ni-CheckNFree4/V1.075/.
cp -f OUTCAR /storage/work/y/yuw3/dfttk/Examples/Ni-CheckNFree4/V1.075/.
cp -f vasprun.xml /storage/work/y/yuw3/dfttk/Examples/Ni-CheckNFree4/V1.075/.

cd /storage/work/y/yuw3/dfttk/Examples/Ni-CheckNFree4/V1.075
if ( -e OUTCAR ) then
	gzip -f DOSCAR
    endif
endif
