#!/bin/csh -f
#
set poscar = "POSCAR"
set task = "-POSCAR_SUBMIT"

set linepbs = ""

set Born = ""

foreach option ( $* )
  if (x$1 == "x-h") then
    echo "USAGE: jrunE    [ -task POSCAR_SUBMIT ]"
    echo "                [ -task COPY_CONTCAR_CONTINUE_JOB ]"
    echo "                [ -task CONTINUE_JOB ]"
    exit
  else if (x$1 == "x-Born") then
    shift
    set Born = "Born"
    continue
  else if (x$1 == "x-task") then
    shift
    set task = "$1"
    if ( $#argv != 0 ) shift
    continue
  else 
    set linepbs = "$linepbs $1"
    if ( $#argv != 0 ) shift
  endif
end

if ( "$task" == "POSCAR_SUBMIT" ) then
    vcmd
    set poscar = "POSCAR"
else if ( "$task" == "COPY_CONTCAR_CONTINUE_JOB" ) then
    cbakE
    set poscar = "CONTCAR"
else if ( "$task" == "CONTINUE_JOB" ) then
    set poscar = "CONTCAR"
endif

set s = "`pwd`"
set h = $s:t

    set d = "E"

        if ( -e $d ) then
        cd $d

vasppbs $linepbs >B-"$h"
set WORKDIR = "`pwd`"
set RUNDIR = '$tmpdir'
set VSPCMD = '$VSPCMD'

cat <<end.end >>B-"$h"
if ( !(-e $RUNDIR) ) mkdir $RUNDIR
cd $WORKDIR
unalias cp
unalias mv
cp -f KPOINTS  $RUNDIR
zcat POTCAR.gz  >$RUNDIR/POTCAR
cp -f INCAR    $RUNDIR
cp -f $poscar   $RUNDIR/POSCAR
cd $RUNDIR
$VSPCMD
cp -f OSZICAR $WORKDIR/Relax.OSZ
cp -f CONTCAR $WORKDIR/Relax.CON
cp -f OUTCAR $WORKDIR/Relax.OUT

grep -v NSW INCAR | grep -v SIGMA |  grep -v ISMEAR >t.m.p.file
echo "ISMEAR=-5" >>t.m.p.file
echo "NSW=0" >>t.m.p.file
mv -f t.m.p.file INCAR

cp -f CONTCAR POSCAR
$VSPCMD
cp -f OSZICAR $WORKDIR/Static.OSZ
cp -f CONTCAR $WORKDIR/Static.CON
cp -f OUTCAR $WORKDIR/Static.OUT
cp -f DOSCAR $WORKDIR/Static.DOS

if ( "$Born" == "Born" ) then
grep -v NSW INCAR | grep -v SIGMA >t.m.p.file
echo "ISMEAR=-5" >>t.m.p.file
echo "LEPSILON=.T." >>t.m.p.file
echo "NSW=0" >>t.m.p.file
mv -f t.m.p.file INCAR
$VSPCMD
cp -f OSZICAR $WORKDIR/OSZICAR
cp -f CONTCAR $WORKDIR/CONTCAR
cp -f OUTCAR $WORKDIR/OUTCAR
endif

cd $WORKDIR
gzip -f Static.OUT
gzip -f Static.DOS
gzip -f Relax.OUT
if ( -e OUTCAR ) gzip -f OUTCAR

end.end

	qsub B-"$h"
        cd ..
	endif

