#!/bin/csh
#PBS -N BV1.015Ni-Ch
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:59:00
cd $PBS_O_WORKDIR
set VSPCMD = "vasp_std"
module load intel impi mkl vasp
set tmpdir = "/gpfs/scratch/yuw3/work_dfttk_Examples_Ni-Check_V1.015"
unalias cp
unalias rm
if ( !(-e $tmpdir) ) mkdir $tmpdir
cd /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015
unalias cp
unalias mv
cp -f KPOINTS  $tmpdir
#cp -f POTCAR   $tmpdir

if ( -e ../tplate/POTCAR ) then
  cp -f ../tplate/POTCAR $tmpdir
else if ( -e ../tplate/POTCAR.gz ) then
  zcat ../tplate/POTCAR.gz   >$tmpdir/POTCAR
else if ( -e ../../POTCAR.gz ) then
  zcat ../../POTCAR.gz   >$tmpdir/POTCAR
endif

cp -f INCAR    $tmpdir
cp -f POSCAR   $tmpdir/POSCAR
cd $tmpdir

$VSPCMD >& $tmpdir/B-"Ni-Check".error

cp -f OSZICAR /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015/.
cp -f CONTCAR /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015/.

if ( "full" == "full" ) then
  cp -f OUTCAR /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015/.
  cp -f DOSCAR /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015/.
else
  tail -500 OUTCAR >/storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015/OUTCAR
endif

cp $tmpdir/B-"Ni-Check".error /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015

if ( "clean" == "clean" && "/storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015" != "$tmpdir" ) then
  set done = '`tail -1 /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015/OSZICAR | grep E0 | wc -l | awk "{print -node}"`'
  set run = "$done"
  if ( "$tmpdir":h != "/storage/home/yuw3" && "$run" != ""0"" ) then
    rm $tmpdir/* 
    rmdir $tmpdir
  endif
endif
cd /storage/work/y/yuw3/dfttk/Examples/Ni-Check/V1.015
if ( -e OUTCAR ) then
    if ( ! -z OUTCAR ) then
	if ( -e OUTCAR.gz ) mv OUTCAR.gz OUTCAR.gz.old
	gzip -f OUTCAR
	if ( -e DOSCAR.gz ) mv DOSCAR.gz DOSCAR.gz.old
	gzip -f DOSCAR
    endif
endif
